import './core/documentos.js';
import { cargarConfiguracion } from './core/config-publica.js';
import { inicializarFirebase } from './core/firebase.js';
import { inicializarDatos } from './core/datos.js';
import { inicializarInterfaz } from './core/interfaz.js';
import { inicializarGastos } from './modulos/gastos.js';
import { inicializarIngresos } from './modulos/ingresos.js';
import { inicializarImportaciones } from './modulos/importaciones.js';
import { inicializarFacturas } from './modulos/facturas.js';
import { inicializarGastosFijos } from './modulos/gastos-fijos.js';
import { inicializarEtiquetas } from './modulos/etiquetas.js';
import { inicializarImei } from './modulos/imei.js';
import { inicializarRepuestos } from './modulos/repuestos.js';
import { inicializarEncargues } from './modulos/encargues.js';
import { inicializarCaja } from './modulos/caja.js';
import { inicializarInicio } from './modulos/inicio.js';
import { inicializarClientes } from './modulos/clientes.js';
import { inicializarPos } from './modulos/pos.js';
import { inicializarInventario } from './modulos/inventario.js';
import { inicializarCostos } from './modulos/costos.js';
import { inicializarWhatsapp } from './modulos/whatsapp.js';
import { inicializarReparaciones } from './modulos/reparaciones.js';
import { inicializarStock } from './modulos/stock.js';
import { inicializarConsignacion } from './modulos/consignacion.js';
import { inicializarReportes } from './modulos/reportes.js';
import { inicializarAmortizaciones } from './modulos/amortizaciones.js';
import { inicializarConfiguracion } from './modulos/configuracion.js';
import { inicializarInstagram } from './modulos/instagram.js';
import { inicializarConocimiento } from './modulos/conocimiento.js';
import { inicializarArca } from './modulos/arca.js';
import { inicializarCatalogo } from './modulos/catalogo.js';
import { inicializarAsistente } from './modulos/asistente.js';
import { inicializarFacturador } from './modulos/facturador.js';
import { inicializarSesion } from './core/sesion.js';

export async function iniciarSistema() {
  await cargarConfiguracion();
  inicializarFirebase();
  inicializarDatos();
  inicializarInterfaz();
  inicializarGastos();
  inicializarIngresos();
  inicializarImportaciones();
  inicializarFacturas();
  inicializarGastosFijos();
  inicializarEtiquetas();
  inicializarImei();
  inicializarRepuestos();
  inicializarEncargues();
  inicializarCaja();
  inicializarInicio();
  inicializarClientes();
  inicializarPos();
  inicializarInventario();
  inicializarCostos();
  inicializarWhatsapp();
  inicializarReparaciones();
  inicializarStock();
  inicializarConsignacion();
  inicializarReportes();
  inicializarAmortizaciones();
  inicializarConfiguracion();
  inicializarInstagram();
  inicializarConocimiento();
  inicializarArca();
  inicializarCatalogo();
  inicializarAsistente();
  inicializarFacturador();
  inicializarSesion();
}

iniciarSistema().catch(error => {
  console.error('No se pudo iniciar MarplaCity:', error);
  const carga = document.getElementById('loading');
  if (carga) carga.textContent = 'No se pudo iniciar el sistema. Recargá la página o revisá si el servidor está abierto.';
});
